export { default as AppMain } from './AppMain.vue'
export { default as Navbar } from './navigation-bar/Index.vue'
export { default as Settings } from './settings/Index.vue'
export { default as Sidebar } from './side-bar/Index.vue'
export { default as TagsView } from './tags-view/Index.vue'
